# This is a basic workflow that is manually triggered
# ワークフロー名の設定
name: Gatsby build and ｄeploy to a server

# master branch へ push したときにこのワークフローを実行するよう指定
on:
  push:
    branches:
      - master

# 以下，jobs の定義
jobs: 
# 「build」という名前のジョブを定義
  build:
# ubuntu の最新版を指定
    runs-on: ubuntu-latest

# 実行する処理やコマンドを指定
    steps:
# レポジトリからの checkout を実行
      - uses: actions/checkout@v2

# Node のセットアップ
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
# Node の実行（npm install, npm run build）        
      - name: Build Project
        run: |
          npm install
          npm run build
# 確認のためのリスト表示　必要なければ削除  
      - name: List output files
        run: ls -laFG
      
# rsync の設定
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.ID_ECDSA_FREEDOM }}
